D8CORE-2610 Deprecation notice about C, G, J, and Q lockup
SU-SWS/decanter pull request #788
Opened 2021-01-12 22:09 UTC by rebeccahongsf

# READY FOR REVIEW

# Summary
- Deprecation notice about C, G, J, and Q lockup

# Needed By (Date)
- Within V6

# Urgency
- Non-urgent

# Steps to Test

# Associated Issues and/or People
-  [D8CORE-2610 ](https://stanfordits.atlassian.net/browse/D8CORE-2610)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2021-01-12 22:32 UTC, sherakama commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr788-blt7lamun86zd3p995zmfttjehdq2ard.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5ffe1e31dc54c3b29f9b3fc4

2021-01-13 00:58 UTC, sherakama commented on DEPRECATIONS.md
> +- Stanford University lockup options C, G, J, and Q (i.e. `.su-lockup--option-c`) will be removed in Version 7.
This notice should be moved to a new heading `Deprecated in 6.2.2` as 6.2.1 has already been released.

Also, I do not see a deprecation comment in the SCSS eg: https://github.com/SU-SWS/decanter/blob/master/core/src/scss/components/lockup/_lockup--option-c.scss

Please add deprecation notice SCSS comment to each of the lockups. EG: https://github.com/SU-SWS/decanter/blob/master/core/src/scss/core/fonts/_fonts.scss#L21 and https://github.com/SU-SWS/decanter/blob/master/core/src/scss/utilities/mixins/modular-scale/_modular-spacing.scss#L22

2021-01-13 00:58 UTC, sherakama requested changes
Some feedback.

2021-01-13 16:48 UTC, sherakama commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr788-blt7lamun86zd3p995zmfttjehdq2ard.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5ffe1e31dc54c3b29f9b3fc4

2021-01-13 16:53 UTC, sherakama commented on DEPRECATIONS.md
> +_Deprecated in 6.2.2_
```suggestion
_Deprecated in 6.2.2_

- Stanford University lockup options C, G, J, and Q (i.e. `.su-lockup--option-c`) will be removed in Version 7.

_Deprecated in 6.2.0_
```

2021-01-13 16:53 UTC, sherakama commented on DEPRECATIONS.md
> +- Stanford University lockup options C, G, J, and Q (i.e. `.su-lockup--option-c`) will be removed in Version 7.
```suggestion
```

2021-01-13 16:54 UTC, sherakama commented on core/src/scss/components/lockup/_lockup.scss
>  // .su-lockup--option-t - Option T
```suggestion
// .su-lockup--option-t - Option T

// @deprecated Options C, G, J, & Q will be removed in Version 7

```

2021-01-13 17:33 UTC, rebeccahongsf commented
Thank you @sherakama for the speedy review and feedback! 😄  

Would you happen to know if the information listed on our [Decanter Lockup page ](https://decanter.stanford.edu/component/identity-lockup/) needs to be deprecated through Netlify/Decanter-web or within this repo? If it's within this repo, I'd like to include it with this PR.

2021-01-13 20:48 UTC, sherakama commented
> Thank you @sherakama for the speedy review and feedback! 😄
> 
> Would you happen to know if the information listed on our [Decanter Lockup page ](https://decanter.stanford.edu/component/identity-lockup/) needs to be deprecated through Netlify/Decanter-web or within this repo? If it's within this repo, I'd like to include it with this PR.

I suppose the answer is both. The code itself should notify developers about deprecations. I cannot remember if we had direct handling on deprecations from SCSS comments but I doubt it. Especially from variants. I would say that the notice would have to be added to the component in the Netlify CMS https://decanter.stanford.edu/admin/index.html#/collections/components/entries/identity-lockup

2021-01-14 21:22 UTC, sherakama commented
@rebeccahongsf it looks like you started from the forms branch. This will need to go into master so you will have to revise your branch and either rebase out the form work or copy over the work into a new branch stemmed off of master.

2021-01-14 22:59 UTC, rebeccahongsf commented
> @rebeccahongsf it looks like you started from the forms branch. This will need to go into master so you will have to revise your branch and either rebase out the form work or copy over the work into a new branch stemmed off of master.

Thanks Shea! I'll move the work over to a new branch off of master and get a PR up tomorrow! 👍

2021-01-20 16:19 UTC, closed without merging