D8CORE-5738 | @jdwjdwjdw | Update global footer and brand bar for A11y
SU-SWS/decanter pull request #913
Opened 2023-05-23 17:39 UTC by jdwjdwjdw

# READY FOR REVIEW

# Summary
- Global footer a11y updates. I am currently blocked in terms of being able to test these changes on my local, so additional work / changes will probably be needed. Please keep me updated on any issues that come up as you review.
- [D8CORE-2730](https://stanfordits.atlassian.net/browse/D8CORE-2730): A11y: in the global footer add "Link is external" for AT to logo
- [D8CORE-5738](https://stanfordits.atlassian.net/browse/D8CORE-5738): A11y | Decanter Global Footer: Links have different text and go to the same place
- [D8CORE-5798](https://stanfordits.atlassian.net/browse/D8CORE-5798): A11y: in the global footer the "Link is external" needs spacing
- I also added a space before the `(link is external)` in the brand bar.

# Needed By (Date)
- When convenient

# Urgency
- Normal

# Steps to Test

1. Checkout branch
2. Review and inspect the global footer on a site
3. [D8CORE-2730](https://stanfordits.atlassian.net/browse/D8CORE-2730): confirm that ` link is external` text has been added to the Logo
4. [D8CORE-5738](https://stanfordits.atlassian.net/browse/D8CORE-5738): confirm that an `aria-describedby` and `id` has been added to connect the two links that go to the same place (The Stanford logo, and the `Stanford Home` link, and that WAVE no longer flags it as a redundant link
5. [D8CORE-5798](https://stanfordits.atlassian.net/browse/D8CORE-5798): confirm that the `link is external` span includes a space at the beginning. I'm not sure if just adding a space is fine, or if we need to add `&nbsp;` - I'm unable to test this work out currently, so let me know if that span is not showing a space

# Associated Issues and/or People
- [D8CORE-2730](https://stanfordits.atlassian.net/browse/D8CORE-2730): A11y: in the global footer add "Link is external" for AT to logo
- [D8CORE-5738](https://stanfordits.atlassian.net/browse/D8CORE-5738): A11y | Decanter Global Footer: Links have different text and go to the same place
- [D8CORE-5798](https://stanfordits.atlassian.net/browse/D8CORE-5798): A11y: in the global footer the "Link is external" needs spacing

[D8CORE-2730]: https://stanfordits.atlassian.net/browse/D8CORE-2730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[D8CORE-5738]: https://stanfordits.atlassian.net/browse/D8CORE-5738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[D8CORE-5798]: https://stanfordits.atlassian.net/browse/D8CORE-5798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[D8CORE-2730]: https://stanfordits.atlassian.net/browse/D8CORE-2730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[D8CORE-5738]: https://stanfordits.atlassian.net/browse/D8CORE-5738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-05-23 20:50 UTC, jenbreese requested changes

2023-05-23 20:50 UTC, jenbreese commented on core/src/templates/components/global-footer/global-footer.twig
On line 21 `<div class="su-global-footer__container" title="Common Stanford resources">` There is a title that shouldn't be there and the non-discrimation link is different.  Can you check on those?

2023-05-23 20:50 UTC, jenbreese commented on core/src/templates/components/global-footer/global-footer.twig
@cjwest That title on the `div` needs to be gone, correct?

2023-05-23 22:57 UTC, closed without merging

2023-05-24 01:07 UTC, cjwest commented on core/src/templates/components/global-footer/global-footer.twig
Yes, please. The title is not accessible without the mouse.

2023-05-24 18:22 UTC, jdwjdwjdw commented on core/src/templates/components/global-footer/global-footer.twig
Thanks Jen and Caryl - this PR was on the wrong branch, and it looks like that title has been removed on the correct branch already. See https://github.com/SU-SWS/decanter/pull/910 for the updated PR on the correct branch.